////////SLENDERMAN

texture XCSCRL01
pic XCSCRL01 tics 1
pic XCSCRL03 tics 1
pic XCSCRL05 tics 1
pic XCSCRL07 tics 1
pic XCSCRL09 tics 1
pic XCSCRL11 tics 1

texture XCSCRL03
pic XCSCRL03 tics 1
pic XCSCRL01 tics 1
pic XCSCRL11 tics 1
pic XCSCRL09 tics 1
pic XCSCRL07 tics 1
pic XCSCRL05 tics 1

texture XCSCRO01
pic XCSCRO01 tics 1
pic XCSCRO02 tics 1
pic XCSCRO03 tics 1
pic XCSCRO04 tics 1

texture XCSCRO04
pic XCSCRO04 tics 1
pic XCSCRO03 tics 1
pic XCSCRO02 tics 1
pic XCSCRO01 tics 1

texture SLANIMA1
pic SLANIMA1 tics 5
pic SLANIMA2 tics 5
pic SLANIMA1 tics 5
pic SLANIMA3 tics 5
pic SLANIMA4 tics 5
pic SLANIMA5 tics 5
pic SLANIMA6 tics 5
pic SLANIMA7 tics 5
pic SLANIMA8 tics 5
pic SLANIMA2 tics 5

//Black water
warp2 texture DIRWAT2
warp2 texture DIRWAT3
warp2 texture DIRWAT4
warp2 texture AZWATER1
warp2 texture AZWATER2
warp2 texture AZWATER3

//////////VOLTANIAN WHEEL

texture VOLTANI1
pic VOLTANI1 tics 51
pic VOLTANI2 tics 51
pic VOLTANI3 tics 51
pic VOLTANI4 tics 51
pic VOLTANI5 tics 71
pic VOLTANI6 tics 71

//// movietheatre bilboard

texture MOVBILB1
pic MOVBILB1 tics 15
pic MOVBILB2 tics 15
pic MOVBILB3 tics 15


texture XCBINOCB
pic XCBINOCB tics 10
pic XCBINOCA tics 10

texture BUDKA1
pic BUDKA1 tics 7
pic BUDKA2 tics 7

//// caleb heart

texture XCBLDX1
pic XCBLDX1 tics 7
pic XCBLDX2 tics 7
pic XCBLDX3 tics 7
pic XCBLDX4 tics 7

texture CHICK
allowdecals
pic CHICK1 tics 4
pic CHICK2 tics 4
pic CHICK3 tics 4
pic CHICK4 tics 4
pic CHICK5 tics 4
pic CHICK6 tics 4
pic CHICK7 tics 4
pic CHICK8 tics 4
pic CHICK9 tics 4
pic CHICK8 tics 4
pic CHICK7 tics 4
pic CHICK6 tics 4
pic CHICK5 tics 4
pic CHICK4 tics 4
pic CHICK3 tics 4
pic CHICK2 tics 4

texture XCHOTEL1
pic XCHOTEL1 tics 51
pic XCHOTEL2 tics 11
pic XCHOTEL1 tics 4
pic XCHOTEL2 tics 11
pic XCHOTEL1 tics 21
pic XCHOTEL2 tics 41
pic XCHOTEL1 tics 3
pic XCHOTEL2 tics 4
pic XCHOTEL1 tics 8
pic XCHOTEL2 tics 11

texture XCHOTEL2
pic XCHOTEL1 tics 51
pic XCHOTEL2 tics 11
pic XCHOTEL1 tics 4
pic XCHOTEL2 tics 11
pic XCHOTEL1 tics 21
pic XCHOTEL2 tics 41
pic XCHOTEL1 tics 3
pic XCHOTEL2 tics 4
pic XCHOTEL1 tics 8
pic XCHOTEL2 tics 11

///TV NOISE

texture TVNOIZ1
pic TVNOIZ1 tics 2
pic TVNOIZ2 tics 2
pic TVNOIZ3 tics 2
pic TVNOIZ4 tics 2

///LCD CLOCK
texture XCLCDCL1
pic XCLCDCL1 tics 35
pic XCLCDCL2 tics 35

warp flat YZTX181A
warp2 texture YZTX4061

cameratexture YZCMTX01 128 64 fit 128 64
cameratexture YZCMTX02 128 64 fit 128 64
cameratexture YZCMTX03 128 64 fit 128 64
cameratexture YZCMTX04 128 64 fit 128 64
cameratexture YZCMTX05 128 64 fit 128 64
cameratexture YZCMTX06 128 64 fit 128 64
cameratexture YZCMTX07 128 64 fit 128 64
cameratexture YZCMTX08 128 64 fit 128 64
cameratexture YZCMTX09 128 64 fit 128 64
cameratexture YZCMTX10 128 64 fit 128 64
warp2 texture YZFIREFR

///IPNNEWS

texture YZIPN2
pic YZIPN2 tics 8
pic YZIPN3 tics 8
pic YZIPN4 tics 8
pic YZIPN5 tics 8
pic YZIPN6 tics 8
pic YZIPN7 tics 8
pic YZIPN8 tics 8
pic YZIPN9 tics 8
pic YZIPN10 tics 8


///TVNOISE

texture YZTVNZ1
pic YZTVNZ1 tics 2
pic YZTVNZ2 tics 2
pic YZTVNZ3 tics 2
pic YZTVNZ4 tics 2

///BAIT&SWITCH

texture YZBATI11
pic YZBATI11 tics 40
pic YZBATI12 tics 30
pic YZBATI11 tics 40
pic YZBATI12 tics 30
pic YZBATI11 tics 40
pic YZBATI12 tics 30
pic YZBATI11 tics 40
pic YZBATI12 tics 100
pic YZBATI13 tics 100
pic YZBATI14 tics 30
pic YZBATI13 tics 100
pic YZBATI14 tics 30
pic YZBATI13 tics 40
pic YZBATI14 tics 30

///TVUACLOGO

texture YZUACA1
pic YZUACA1 tics 2
pic YZUACA2 tics 2
pic YZUACA3 tics 2
pic YZUACA4 tics 2
pic YZUACA5 tics 2
pic YZUACA6 tics 2
pic YZUACA7 tics 2
pic YZUACA8 tics 2
pic YZUACA9 tics 2
pic YZUACA10 tics 2
pic YZUACA11 tics 2
pic YZUACA12 tics 2
pic YZUACA13 tics 2
pic YZUACA14 tics 2
pic YZUACA15 tics 2
pic YZUACA16 tics 2
pic YZUACA17 tics 2
pic YZUACA18 tics 2
pic YZUACA19 tics 2
pic YZUACA20 tics 2
pic YZUACA21 tics 2
pic YZUACA20 tics 2
pic YZUACA19 tics 2
pic YZUACA18 tics 2
pic YZUACA17 tics 2
pic YZUACA16 tics 2
pic YZUACA15 tics 2
pic YZUACA14 tics 2
pic YZUACA13 tics 2
pic YZUACA12 tics 2
pic YZUACA11 tics 2
pic YZUACA10 tics 2
pic YZUACA9 tics 2
pic YZUACA8 tics 2
pic YZUACA7 tics 2
pic YZUACA6 tics 2
pic YZUACA5 tics 2
pic YZUACA4 tics 2
pic YZUACA3 tics 2
pic YZUACA2 tics 2

/////TV_SUPAROCKITZ

texture YZROCKA1
pic YZROCKA1 tics 2
pic YZROCKA2 tics 2
pic YZROCKA3 tics 2
pic YZROCKA4 tics 2
pic YZROCKA5 tics 2
pic YZROCKA6 tics 2



//////MEMO_TOILETSTORY
texture SORTIR1
pic SORTIR1 tics 6
pic SORTIR2 tics 6
pic SORTIR3 tics 6
pic SORTIR4 tics 6
pic SORTIR3 tics 6
pic SORTIR2 tics 6

/////MEMO_NizhniyKusok

texture YZPOSA11
pic YZPOSA11 tics 6
pic YZPOSA12 tics 6
pic YZPOSA13 tics 6
pic YZPOSA14 tics 6
pic YZPOSA13 tics 6
pic YZPOSA12 tics 6

//////MEMO_xbox
texture POSLMNG1
pic POSLMNG1 tics 6
pic POSLMNG2 tics 6
pic POSLMNG3 tics 6
pic POSLMNG4 tics 6
pic POSLMNG3 tics 6
pic POSLMNG2 tics 6

//////MEMO_NEWS
texture POSLNSP1
pic POSLNSP1 tics 6
pic POSLNSP2 tics 6
pic POSLNSP3 tics 6
pic POSLNSP4 tics 6
pic POSLNSP3 tics 6
pic POSLNSP2 tics 6

//////MEMO_CAPO
texture POSLCAP1
pic POSLCAP1 tics 6
pic POSLCAP2 tics 6
pic POSLCAP3 tics 6
pic POSLCAP4 tics 6
pic POSLCAP3 tics 6
pic POSLCAP2 tics 6

//////MEMO_CAUTION
texture POSLCAU1
pic POSLCAU1 tics 6
pic POSLCAU2 tics 6
pic POSLCAU3 tics 6
pic POSLCAU4 tics 6
pic POSLCAU3 tics 6
pic POSLCAU2 tics 6

//////MEMO_CREDITS
texture PISMO1
pic PISMO1 tics 6
pic PISMO2 tics 6
pic PISMO3 tics 6
pic PISMO4 tics 6
pic PISMO3 tics 6
pic PISMO2 tics 6

//////MEMO_COMISC
texture KOMIKSX1
pic KOMIKSX1 tics 6
pic KOMIKSX2 tics 6
pic KOMIKSX3 tics 6
pic KOMIKSX4 tics 6
pic KOMIKSX3 tics 6
pic KOMIKSX2 tics 6


//////MEMO_Translator
texture POSLTRA1
pic POSLTRA1 tics 6
pic POSLTRA2 tics 6
pic POSLTRA3 tics 6
pic POSLTRA4 tics 6
pic POSLTRA3 tics 6
pic POSLTRA2 tics 6


//////MEMO_firstpartletter
texture POSLLT11
pic POSLLT11 tics 6
pic POSLLT12 tics 6
pic POSLLT13 tics 6
pic POSLLT14 tics 6
pic POSLLT13 tics 6
pic POSLLT12 tics 6

//////MEMO_newspapergang
texture ANLET101
pic ANLET101 tics 6
pic ANLET102 tics 6
pic ANLET103 tics 6
pic ANLET104 tics 6
pic ANLET103 tics 6
pic ANLET102 tics 6


//////MATRIX
texture YZMATRI1
pic YZMATRI1 tics 2
pic YZMATRI2 tics 2
pic YZMATRI3 tics 2
pic YZMATRI4 tics 2
pic YZMATRI5 tics 2
pic YZMATRI6 tics 2

texture teleptx1
pic TELEPTX1 tics 2
pic TELEPTX2 tics 2
pic TELEPTX3 tics 2
pic TELEPTX4 tics 2
pic TELEPTX5 tics 2
pic TELEPTX6 tics 2
pic TELEPTX7 tics 2
pic TELEPTX8 tics 2
pic TELEPTX9 tics 2
pic TELEPTXA tics 2

texture PDATX1
pic PDATX1 tics 6
pic PDATX2 tics 6
pic PDATX3 tics 6
pic PDATX4 tics 6
pic PDATX3 tics 6
pic PDATX2 tics 6

texture YZPCSCR1
pic YZPCSCR1 tics 16
pic YZPCSCR2 tics 16

texture YZCPUP1
pic YZCPUP1 tics 21
pic YZCPUP2 tics 21

///RUTABAGASALAD

texture YZRTBGS1
pic YZRTBGS1 tics 7
pic YZRTBGS2 tics 7
pic YZRTBGS3 tics 7
pic YZRTBGS4 tics 7

//CC3

texture CC3SCR1
pic CC3SCR1 tics 2
pic CC3SCR2 tics 2
pic CC3SCR3 tics 2
pic CC3SCR4 tics 2

texture CC3LASR1
pic CC3LASR1 tics 1
pic CC3LASR2 tics 1

//////////Curtain eyes
texture CTCURT1
pic CTCURT1 tics 70
pic CTCURT2 tics 385
pic CTCURT1 tics 45
pic CTCURT2 tics 25
pic CTCURT1 tics 100
pic CTCURT2 tics 500