texture YZTX3105, 128, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZTX3105, 0, 0
  {
  }
}

texture YZMWMAP1, 480, 300
{
  XScale 4.0
  YScale 4.0
  Patch YZMWMAP1, 0, 0
  {
  }
}

texture YZOTKLU4, 96, 96
{
  XScale 2.0
  YScale 2.0
  Patch YZOTKLU4, 0, 0
  {
  }
}

texture YZTX596, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX596, 0, 0
  {
  }
}

texture SNES1, 64, 64
{
  XScale 2.0
  YScale 2.0
  Patch SNES1, 0, 0
  {
  }
}

texture SNES2, 64, 32
{
  XScale 2.0
  YScale 2.0
  Patch SNES2, 0, 0
  {
  }
}

texture SNES3, 192, 88
{
  XScale 8.0
  YScale 8.0
  Patch SNES3, 0, 0
  {
  }
}

texture SNES4, 32, 64
{
  XScale 2.0
  YScale 2.0
  Patch SNES4, 0, 0
  {
  }
}

texture PS2A, 96, 56
{
  XScale 2.0
  YScale 2.0
  Patch PS2A, 0, 0
  {
  }
}

texture PS2B, 64, 42
{
  XScale 2.0
  YScale 2.0
  Patch PS2B, 0, 0
  {
  }
}

texture PS2C, 512, 512
{
  XScale 8.0
  YScale 8.0
  Patch PS2C, 0, 0
  {
  }
}

texture YZTX1047, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX1047, 0, 0
  {
  }
}

texture YZTX1156, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX1156, 0, 0
  {
  }
}

texture YZTX1169, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX1169, 0, 0
  {
  }
}

texture YZTX1466, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX1466, 0, 0
  {
  }
}

texture YZTX1824, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX1824, 0, 0
  {
  }
}

texture YZTX2503, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2503, 0, 0
  {
  }
}

texture YZTX2835, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2835, 0, 0
  {
  }
}

texture YZTX2643, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX2643, 0, 0
  {
  }
}

texture YZELEVSH, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZELEVSH, 0, 0
  {
  }
}

texture YZTX2644, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX2644, 0, 0
  {
  }
}

texture YZTX2645, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX2645, 0, 0
  {
  }
}

texture YZTX2646, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX2646, 0, 0
  {
  }
}

texture YZTX2647, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX2647, 0, 0
  {
  }
}

texture YZTX2648, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX2648, 0, 0
  {
  }
}


texture YZTX2651, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX2651, 0, 0
  {
  }
}

texture YZTX449, 256, 256
{
  XScale 4.0
  YScale 4.0
  Patch YZTX449, 0, 0
  {
  }
}

texture YZTX811, 256, 256
{
  XScale 4.0
  YScale 4.0
  Patch YZTX811, 0, 0
  {
  }
}

texture YZTX1158, 256, 256
{
  XScale 4.0
  YScale 4.0
  Patch YZTX1158, 0, 0
  {
  }
}

texture YZTX3449, 256, 256
{
  XScale 4.0
  YScale 4.0
  Patch YZTX3449, 0, 0
  {
  }
}

texture YZTX3524, 256, 256
{
  XScale 4.0
  YScale 4.0
  Patch YZTX3524, 0, 0
  {
  }
}

texture YZTX2669, 512, 512
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2669, 0, 0
  {
  }
}

texture YZTX267A, 512, 512
{
  XScale 4.0
  YScale 4.0
  Patch YZTX267A, 0, 0
  {
  }
}

texture YZTLEPT, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZTLEPT, 0, 0
  {
  }
}

texture YZTX2909, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2909, 0, 0
  {
  }
}

texture YZFLRW1, 256, 256
{
  XScale 8.0
  YScale 8.0
  Patch YZFLRW1, 0, 0
  {
  }
}

texture YZTX881, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX881, 0, 0
  {
  }
}

texture YZTX884, 256, 256
{
  XScale 4.0
  YScale 4.0
  Patch YZTX884, 0, 0
  {
  }
}

texture YZTX1201, 1024, 1024
{
  XScale 8.0
  YScale 8.0
  Patch YZTX1201, 0, 0
  {
  }
}

texture YZTX2094, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2094, 0, 0
  {
  }
}


texture YZTX2095, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2095, 0, 0
  {
  }
}


texture YZTX2096, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2096, 0, 0
  {
  }
}


texture YZTX2097, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2097, 0, 0
  {
  }
}


texture YZTX2098, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2098, 0, 0
  {
  }
}


texture YZTX2099, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2099, 0, 0
  {
  }
}


texture YZTX2100, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2100, 0, 0
  {
  }
}


texture YZTX2101, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2101, 0, 0
  {
  }
}


texture YZTX2102, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2102, 0, 0
  {
  }
}

texture YZXBX2, 405, 242
{
  XScale 10.0
  YScale 10.0
  Patch YZXBX2, 0, 0
  {
  }
}


texture YZTX2103, 64, 64
{
  XScale 4.0
  YScale 4.0
  Patch YZTX2103, 0, 0
  {
  }
}

texture YZTX3241, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX3241, 0, 0
  {
  }
}

texture YZWRACK1, 512, 256
{
  XScale 8.0
  YScale 8.0
  Patch YZWRACK1, 0, 0
  {
  }
}


texture PDATX1, 32, 50
{
  XScale 2.0
  YScale 2.0
  Patch PDATX1, 0, 0
  {
  }
}
texture PDATX2, 32, 50
{
  XScale 2.0
  YScale 2.0
  Patch PDATX2, 0, 0
  {
  }
}
texture PDATX3, 32, 50
{
  XScale 2.0
  YScale 2.0
  Patch PDATX3, 0, 0
  {
  }
}
texture PDATX4, 32, 50
{
  XScale 2.0
  YScale 2.0
  Patch PDATX4, 0, 0
  {
  }
}
texture YZHACKTX, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZHACKTX, 0, 0
  {
  }
}

texture YZBATI11, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBATI11, 0, 0
  {
  }
}

texture YZBATI12, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBATI12, 0, 0
  {
  }
}

texture YZBATI13, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBATI13, 0, 0
  {
  }
}

texture YZBATI14, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBATI14, 0, 0
  {
  }
}
texture YZIPN1, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN1, 0, 0
  {
  }
}

texture YZIPN2, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN2, 0, 0
  {
  }
}

texture YZIPN3, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN3, 0, 0
  {
  }
}
texture YZIPN4, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN4, 0, 0
  {
  }
}
texture YZIPN5, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN5, 0, 0
  {
  }
}
texture YZIPN6, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN6, 0, 0
  {
  }
}
texture YZIPN7, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN7, 0, 0
  {
  }
}
texture YZIPN8, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN8, 0, 0
  {
  }
}
texture YZIPN9, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN9, 0, 0
  {
  }
}
texture YZIPN10, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZIPN10, 0, 0
  {
  }
}

texture YZBAIT1, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT1, 0, 0
  {
  }
}

texture YZBAIT2, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT2, 0, 0
  {
  }
}

texture YZBAIT3, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT3, 0, 0
  {
  }
}

texture YZBAIT4, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT4, 0, 0
  {
  }
}

texture YZBAIT5, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT5, 0, 0
  {
  }
}

texture YZBAIT6, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT6, 0, 0
  {
  }
}

texture YZBAIT7, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT7, 0, 0
  {
  }
}

texture YZBAIT8, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT8, 0, 0
  {
  }
}

texture YZBAIT9, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT9, 0, 0
  {
  }
}

texture YZBAIT10, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT10, 0, 0
  {
  }
}

texture YZBAIT11, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT11, 0, 0
  {
  }
}

texture YZBAIT12, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT12, 0, 0
  {
  }
}

texture YZBAIT13, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT13, 0, 0
  {
  }
}

texture YZBAIT14, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT14, 0, 0
  {
  }
}

texture YZBAIT15, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT15, 0, 0
  {
  }
}

texture YZBAIT16, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT16, 0, 0
  {
  }
}

texture YZBAIT17, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT17, 0, 0
  {
  }
}

texture YZBAIT18, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT18, 0, 0
  {
  }
}

texture YZBAIT19, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT19, 0, 0
  {
  }
}

texture YZBAIT20, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBAIT20, 0, 0
  {
  }
}

texture YZTVNZ1, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZTVNZ1, 0, 0
  {
  }
}

texture YZTVNZ2, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZTVNZ2, 0, 0
  {
  }
}


texture YZTVNZ3, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZTVNZ3, 0, 0
  {
  }
}


texture YZTVNZ4, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZTVNZ4, 0, 0
  {
  }
}


texture YZUACA1, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA1, 0, 0
  {
  }
}


texture YZUACA2, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA2, 0, 0
  {
  }
}


texture YZUACA3, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA3, 0, 0
  {
  }
}


texture YZUACA4, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA4, 0, 0
  {
  }
}


texture YZUACA5, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA5, 0, 0
  {
  }
}


texture YZUACA6, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA6, 0, 0
  {
  }
}


texture YZUACA7, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA7, 0, 0
  {
  }
}


texture YZUACA8, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA8, 0, 0
  {
  }
}


texture YZUACA9, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA9, 0, 0
  {
  }
}


texture YZUACA10, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA10, 0, 0
  {
  }
}


texture YZUACA11, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA11, 0, 0
  {
  }
}


texture YZUACA12, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA12, 0, 0
  {
  }
}


texture YZUACA13, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA13, 0, 0
  {
  }
}


texture YZUACA14, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA14, 0, 0
  {
  }
}


texture YZUACA15, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA15, 0, 0
  {
  }
}


texture YZUACA16, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA16, 0, 0
  {
  }
}


texture YZUACA17, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA17, 0, 0
  {
  }
}


texture YZUACA18, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA18, 0, 0
  {
  }
}


texture YZUACA19, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA19, 0, 0
  {
  }
}


texture YZUACA20, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA20, 0, 0
  {
  }
}


texture YZUACA21, 256, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZUACA21, 0, 0
  {
  }
}

texture YZROCKA1, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZROCKA1, 0, 0
  {
  }
}

texture YZROCKA2, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZROCKA2, 0, 0
  {
  }
}
texture YZROCKA3, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZROCKA3, 0, 0
  {
  }
}
texture YZROCKA4, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZROCKA4, 0, 0
  {
  }
}
texture YZROCKA5, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZROCKA5, 0, 0
  {
  }
}
texture YZROCKA6, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZROCKA6, 0, 0
  {
  }
}


texture USS1, 128, 384
{
  XScale 4.0
  YScale 4.0
  Patch USS1, 0, 0
  {
  }
}

texture USS2, 128, 384
{
  XScale 4.0
  YScale 4.0
  Patch USS2, 0, 0
  {
  }
}

texture YZTHRST, 128, 256
{
  XScale 2.5
  YScale 2.5
  Patch YZTHRST, 0, 0
  {
  }
}

texture YZCOCACO, 128, 256
{
  XScale 2.5
  YScale 2.5
  Patch YZCOCACO, 0, 0
  {
  }
}

texture YZXRAY1, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZXRAY1, 0, 0
  {
  }
}

texture YZXRAY2, 256, 192
{
  XScale 4.0
  YScale 4.0
  Patch YZXRAY2, 0, 0
  {
  }
}

texture YZXRAY3, 128, 228
{
  XScale 2.0
  YScale 2.0
  Patch YZXRAY3, 0, 0
  {
  }
}

texture YZCCCKDR, 256, 512
{
  XScale 4.0
  YScale 4.0
  Patch YZCCCKDR, 0, 0
  {
  }
}

texture YZXBOX01, 256, 363
{
  XScale 16.0
  YScale 16.0
  Patch YZXBOX01, 0, 0
  {
  }
}

texture YZXBOX02, 363, 269
{
  XScale 16.0
  YScale 16.0
  Patch YZXBOX02, 0, 0
  {
  }
}

texture YZWRACK3, 256, 231
{
  XScale 8.0
  YScale 8.0
  Patch YZWRACK3, 0, 0
  {
  }
}

texture YZBLDHND, 64, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZBLDHND, 0, 0
  {
  }
}

texture YZSWANFX, 128, 96
{
  XScale 2.0
  YScale 2.0
  Patch YZSWANFX, 0, 0
  {
  }
}

texture YZPLATE1, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZPLATE1, 0, 0
  {
  }
}

texture YZPLATE2, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZPLATE2, 0, 0
  {
  }
}
texture YZPLATE3, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZPLATE3, 0, 0
  {
  }
}
texture YZPLATE4, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZPLATE4, 0, 0
  {
  }
}
texture YZPLATE5, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZPLATE5, 0, 0
  {
  }
}

texture YZSTANDH, 128, 128
{
  XScale 4.0
  YScale 4.0
  Patch YZSTANDH, 0, 0
  {
  }
}

texture YZLVL4DR, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZLVL4DR, 0, 0
  {
  }
}


texture YZLVL7DR, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch YZLVL7DR, 0, 0
  {
  }
}

texture YZWCDR01, 128, 192
{
  XScale 2.0
  YScale 2.0
  Patch YZWCDR01, 0, 0
  {
  }
}

texture YZWCDR02, 128, 192
{
  XScale 2.0
  YScale 2.0
  Patch YZWCDR02, 0, 0
  {
  }
}

texture YZPLTFT3, 80, 40
{
  XScale 2.0
  YScale 2.0
  Patch YZPLTFT3, 0, 0
  {
  }
}

texture YZPLTFT2, 80, 40
{
  XScale 2.0
  YScale 2.0
  Patch YZPLTFT2, 0, 0
  {
  }
}

texture YZCHAIHI, 256, 130
{
  XScale 4.0
  YScale 4.0
  Patch YZCHAIHI, 0, 0
  {
  }
}

texture YZNOSMOK, 64, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZNOSMOK, 0, 0
  {
  }
  }
  
texture YZPSTER1, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZPSTER1, 0, 0
  {
  }
}

texture YZPSTER2, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZPSTER2, 0, 0
  {
  }
}

texture YZPSTER3, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZPSTER3, 0, 0
  {
  }
}

texture YZPSTER4, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZPSTER4, 0, 0
  {
  }
}

texture YZWARNP1, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZWARNP1, 0, 0
  {
  }
}

texture YZWARNP2, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZWARNP2, 0, 0
  {
  }
}

texture YZWARNP3, 64, 92
{
  XScale 4.0
  YScale 4.0
  Patch YZWARNP3, 0, 0
  {
  }
}

texture YZAIDSST, 50, 80
{
  XScale 2.0
  YScale 2.0
  Patch YZAIDSST, 0, 0
  {
  }
}



texture YZTX1126, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch YZTX1126, 0, 0
  {
  }
}

texture YZTX811, 256, 256
{
  XScale 4.0
  YScale 4.0
  Patch YZTX811, 0, 0
  {
  }
}

texture YZTX4085, 128, 60
{
  XScale 2.0
  YScale 2.0
  Patch YZTX4085, 0, 0
  {
  }
}


texture YZTOMOON, 96, 200
{
  XScale 2.0
  YScale 2.0
  Patch YZTOMOON, 0, 0
  {
  }
}

texture USSC2, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch USSC2, 0, 0
  {
  }
}

texture USSC3, 128, 256
{
  XScale 2.0
  YScale 2.0
  Patch USSC3, 0, 0
  {
  }
}

texture YZMARSFL, 128, 254
{
  XScale 2.0
  YScale 2.0
  Patch YZMARSFL, 0, 0
  {
  }
}

texture YZMAR2FL, 128, 254
{
  XScale 2.0
  YScale 2.0
  Patch YZMAR2FL, 0, 0
  {
  }
}

texture YZCODER3, 32, 32
{
  XScale 2.0
  YScale 2.0
  Patch YZCODER3, 0, 0
  {
  }
}

texture YZAIRLOK, 1024, 1024
{
  XScale 8.0
  YScale 8.0
  Patch YZAIRLOK, 0, 0
  {
  }
}

texture YZCPUP1, 128, 99
{
  XScale 4.0
  YScale 4.0
  Patch YZCPUP1, 0, 0
  {
  }
}

texture YZCPUP2, 128, 99
{
  XScale 4.0
  YScale 4.0
  Patch YZCPUP2, 0, 0
  {
  }
}

texture YZPCSCR1, 128, 100
{
  XScale 4.0
  YScale 4.0
  Patch YZPCSCR1, 0, 0
  {
  }
}

texture YZPCSCR2, 128, 100
{
  XScale 4.0
  YScale 4.0
  Patch YZPCSCR2, 0, 0
  {
  }
}

texture YZRTBGS1, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZRTBGS1, 0, 0
  {
  }
}

texture YZRTBGS2, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZRTBGS2, 0, 0
  {
  }
}

texture YZRTBGS3, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZRTBGS3, 0, 0
  {
  }
}

texture YZRTBGS4, 128, 64
{
  XScale 2.0
  YScale 2.0
  Patch YZRTBGS4, 0, 0
  {
  }
}


texture XCTX0071, 128, 128
{
  XScale 2.0
  YScale 2.0
  Patch XCTX0071, 0, 0
  {
  }
}

texture DEFEND1, 73, 200
{
  XScale 2.0
  YScale 2.0
  Patch DEFEND1, 0, 0
  {
  }
}

texture DEFEND4, 73, 200
{
  XScale 2.0
  YScale 2.0
  Patch DEFEND4, 0, 0
  {
  }
}

texture DEFEND7, 73, 200
{
  XScale 2.0
  YScale 2.0
  Patch DEFEND7, 0, 0
  {
  }
}

texture DEFEND10, 73, 200
{
  XScale 2.0
  YScale 2.0
  Patch DEFEND10, 0, 0
  {
  }
}
texture DEFEND13, 73, 200
{
  XScale 2.0
  YScale 2.0
  Patch DEFEND13, 0, 0
  {
  }
}

texture DEFEND14, 74, 174
{
  XScale 2.0
  YScale 2.0
  Patch DEFEND14, 0, 0
  {
  }
}

texture DEFEND15, 74, 174
{
  XScale 2.0
  YScale 2.0
  Patch DEFEND15, 0, 0
  {
  }
}

texture XCTXTCF1, 95, 190
{
  XScale 4.0
  YScale 4.0
  Patch XCTXTCF1, 0, 0
  {
  }
}

texture XCTXTCF2, 95, 190
{
  XScale 4.0
  YScale 4.0
  Patch XCTXTCF2, 0, 0
  {
  }
}

texture XSBITARD, 236, 148
{
  XScale 2.0
  YScale 2.0
  Patch XSBITARD, 0, 0
  {
  }
}

texture XCHDNEW1, 910, 574
{
  XScale 16.0
  YScale 16.0
  Patch XCHDNEW1, 0, 0
  {
  }
}

texture XCHDNEW2, 720, 480
{
  XScale 16.0
  YScale 16.0
  Patch XCHDNEW2, 0, 0
  {
  }
}

texture XCSTRT01, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT01, 0, 0
  {
  }
}

texture XCSTRT02, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT02, 0, 0
  {
  }
}

texture XCSTRT03, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT03, 0, 0
  {
  }
}

texture XCSTRT04, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT04, 0, 0
  {
  }
}

texture XCSTRT05, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT05, 0, 0
  {
  }
}

texture XCSTRT06, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT06, 0, 0
  {
  }
}

texture XCSTRT07, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT07, 0, 0
  {
  }
}

texture XCSTRT08, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT08, 0, 0
  {
  }
}

texture XCSTRT09, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT09, 0, 0
  {
  }
}

texture XCSTRT10, 121, 19
{
  XScale 2.0
  YScale 2.0
  Patch XCSTRT10, 0, 0
  {
  }
}

texture SLTXPG11, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG11, 0, 0
  {
  }
}

texture SLTRUC10, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch SLTRUC10, 0, 0
  {
  }
}

texture SLTRUC11, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch SLTRUC11, 0, 0
  {
  }
}

texture SLTRUC12, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch SLTRUC12, 0, 0
  {
  }
}

texture SLTRUC13, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch SLTRUC13, 0, 0
  {
  }
}

texture SLTRUC14, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch SLTRUC14, 0, 0
  {
  }
}

texture SLTRUC15, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch SLTRUC15, 0, 0
  {
  }
}

texture SLTRUC16, 256, 256
{
  XScale 2.0
  YScale 2.0
  Patch SLTRUC16, 0, 0
  {
  }
}

texture SLTXPG11, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG11, 0, 0
  {
  }
}

texture SLTXPG22, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG22, 0, 0
  {
  }
}

texture SLTXPG33, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG33, 0, 0
  {
  }
}

texture SLTXPG44, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG44, 0, 0
  {
  }
}

texture SLTXPG55, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG55, 0, 0
  {
  }
}

texture SLTXPG66, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG66, 0, 0
  {
  }
}

texture SLTXPG77, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG77, 0, 0
  {
  }
}

texture SLTXPG88, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPG88, 0, 0
  {
  }
}

texture SLTXPGSS, 178, 256
{
  XScale 16.0
  YScale 16.0
  Patch SLTXPGSS, 0, 0
  {
  }
}

texture SLMURD01, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD01, 0, 0
  {
  }
}

texture SLMURD02, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD02, 0, 0
  {
  }
}

texture SLMURD03, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD03, 0, 0
  {
  }
}
texture SLMURD04, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD04, 0, 0
  {
  }
}
texture SLMURD05, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD05, 0, 0
  {
  }
}
texture SLMURD06, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD06, 0, 0
  {
  }
}
texture SLMURD07, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD07, 0, 0
  {
  }
}
texture SLMURD08, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD08, 0, 0
  {
  }
}

texture SLMURD09, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD09, 0, 0
  {
  }
}

texture SLMURD10, 160, 88
{
  XScale 2.0
  YScale 2.0
  Patch SLMURD10, 0, 0
  {
  }
}

texture POSLANB, 388, 480
{
  XScale 16.0
  YScale 16.0
  Patch POSLANB, 0, 0
  {
  }
}
texture POSLANC, 435, 480
{
  XScale 16.0
  YScale 16.0
  Patch POSLANC, 0, 0
  {
  }
}
texture POSLAND, 499, 480
{
  XScale 16.0
  YScale 16.0
  Patch POSLAND, 0, 0
  {
  }
}
texture POSLANE, 369, 480
{
  XScale 16.0
  YScale 16.0
  Patch POSLANE, 0, 0
  {
  }
}
texture POSLANF, 324, 460
{
  XScale 16.0
  YScale 16.0
  Patch POSLANF, 0, 0
  {
  }
}
texture POSLANG, 447, 392
{
  XScale 16.0
  YScale 16.0
  Patch POSLANG, 0, 0
  {
  }
}
texture POSLANK, 477, 360
{
  XScale 16.0
  YScale 16.0
  Patch POSLANK, 0, 0
  {
  }
}
texture POSLANM, 401, 479
{
  XScale 16.0
  YScale 16.0
  Patch POSLANM, 0, 0
  {
  }
}

texture PDATX5, 512, 800
{
  XScale 32.0
  YScale 32.0
  Patch PDATX5, 0, 0
  {
  }
}

texture SH4RM1, 184, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM1, 0, 0
  {
  }
}

texture SH4RM2, 180, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM2, 0, 0
  {
  }
}

texture SH4RM3L, 492, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM3L, 0, 0
  {
  }
}

texture SH4RM3R, 492, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM3R, 0, 0
  {
  }
}

texture SH4RM4L, 322, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM4L, 0, 0
  {
  }
}

texture SH4RM4, 184, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM4, 0, 0
  {
  }
}



texture SH4RM4R, 184, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM4R, 0, 0
  {
  }
}

texture SH4RM5L, 220, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM5L, 0, 0
  {
  }
}

texture SH4RM5L2, 23, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM5L2, 0, 0
  {
  }
}

texture SH4RM6D, 202, 86
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM6D, 0, 0
  {
  }
}

texture SH4RM6M, 389, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM6M, 0, 0
  {
  }
}

texture SH4RM6U, 202, 90
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM6U, 0, 0
  {
  }
}

texture SH4RM7, 118, 90
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM7, 0, 0
  {
  }
}

texture SH4RM7D, 120, 85
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM7D, 0, 0
  {
  }
}

texture SH4RM8, 69, 90
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM8, 0, 0
  {
  }
}


texture SH4RM8D, 69, 85
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM8D, 0, 0
  {
  }
}

texture SH4RM9, 104, 50
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM9, 0, 0
  {
  }
}

texture SH4RM9D, 102, 95
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM9D, 0, 0
  {
  }
}

texture SH4RM10, 589, 85
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM10, 0, 0
  {
  }
}

texture SH4RM11, 629, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM11, 0, 0
  {
  }
}

texture SH4RM12, 614, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM12, 0, 0
  {
  }
}

texture SH4RM14, 522, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM14, 0, 0
  {
  }
}

texture SH4RM15, 272, 492
{
  XScale 5.12
  YScale 5.12
  Patch SH4RM15, 0, 0
  {
  }
}

texture SH4RM16, 763, 246
{
  XScale 2.56
  YScale 2.56
  Patch SH4RM16, 0, 0
  {
  }
}

texture SH4RMFR1, 86, 156
{
  XScale 2.56
  YScale 2.56
  Patch SH4RMFR1, 0, 0
  {
  }
}

texture SH4RMFR2, 72, 156
{
  XScale 2.56
  YScale 2.56
  Patch SH4RMFR2, 0, 0
  {
  }
}

texture SH4RMFR3, 87, 46
{
  XScale 2.56
  YScale 2.56
  Patch SH4RMFR3, 0, 0
  {
  }
}
flat SH4RMF1, 180, 427
{
  XScale 2.5
  YScale 2.56
  Patch SH4RMF1, 0, 0
  {
  }
}


flat SH4RMC1, 180, 427
{
  XScale 2.40
  YScale 2.56
  Patch SH4RMC1, 0, 0
  {
  }
}

texture SH4RMD1, 116, 222
{
  XScale 2.56
  YScale 2.56
  Patch SH4RMD1, 0, 0
  {
  }
}

texture SH4RMD2, 116, 222
{
  XScale 2.56
  YScale 2.56
  Patch SH4RMD2, 0, 0
  {
  }
}

texture VOLTANI1, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VOLTANI1, 0, 0
  {
  }
}

texture VOLTANI2, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VOLTANI2, 0, 0
  {
  }
}

texture VOLTANI3, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VOLTANI3, 0, 0
  {
  }
}

texture VOLTANI4, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VOLTANI4, 0, 0
  {
  }
}

texture VOLTANI5, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VOLTANI5, 0, 0
  {
  }
}

texture VOLTANI6, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VOLTANI6, 0, 0
  {
  }
}

texture VWHEEL1A, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VWHEEL1A, 0, 0
  {
  }
}

texture VWHEEL2A, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VWHEEL2A, 0, 0
  {
  }
}

texture VWHEEL3A, 736, 736
{
  XScale 0.5
  YScale 0.5
  Patch VWHEEL3A, 0, 0
  {
  }
}

texture STALLEX, 712, 712
{
  XScale 4.0
  YScale 4.0
  Patch STALLEX, 0, 0
  {
  }
}

texture STALLEXA, 712, 712
{
  XScale 4.0
  YScale 4.0
  Patch STALLEXA, 0, 0
  {
  }
}

texture STALLEXB, 712, 712
{
  XScale 4.0
  YScale 4.0
  Patch STALLEXB, 0, 0
  {
  }
}

texture YZHOWTO, 237, 89
{
  XScale 4.5
  YScale 4.5
  Patch YZHOWTO, 0, 0
  {
  }
}

texture MARSMENU, 1200, 544
{
  XScale 4.0
  YScale 4.0
  Patch MARSMENU, 0, 0
  {
  }
}

texture YZSAVEP, 1200, 147
{
  XScale 8.0
  YScale 8.0
  Patch YZSAVEP, 0, 0
  {
  }
}

graphic M_WDIEX, 104, 76
{
  XScale 4.0
  YScale 4.0
  Patch M_WDIEX, 0, 0
  {
  }
}

//MGZ

texture MGFL001, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL001, 0, 0
  {
  }
}

texture MGFL002, 16, 8
{
  XScale 0.25
  YScale 0.25
  Patch MGFL002, 0, 0
  {
  }
}

texture MGFL003, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL003, 0, 0
  {
  }
}

texture MGFL003B, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL003B, 0, 0
  {
  }
}

texture MGFL003C, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL003C, 0, 0
  {
  }
}

texture MGFL003D, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL003D, 0, 0
  {
  }
}

texture MGFL006, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL006, 0, 0
  {
  }
}

texture MGFL006B, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL006B, 0, 0
  {
  }
}

texture MGFL007, 32, 16
{
  XScale 0.25
  YScale 0.25
  Patch MGFL007, 0, 0
  {
  }
}

texture MGFL009, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL009, 0, 0
  {
  }
}

texture MGFL009B, 32, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGFL009B, 0, 0
  {
  }
}
texture MGFL010, 6, 6
{
  XScale 0.25
  YScale 0.25
  Patch MGFL010, 0, 0
  {
  }
}

texture MGFL011, 8, 7
{
  XScale 0.25
  YScale 0.25
  Patch MGFL011, 0, 0
  {
  }
}

texture MGFL012, 30, 42
{
  XScale 0.25
  YScale 0.25
  Patch MGFL012, 0, 0
  {
  }
}

texture MGFL012B, 45, 63
{
  XScale 0.25
  YScale 0.25
  Patch MGFL012B, 0, 0
  {
  }
}

texture MGFL012C, 45, 63
{
  XScale 0.25
  YScale 0.25
  Patch MGFL012C, 0, 0
  {
  }
}
texture TMP001, 568, 726
{
  XScale 0.25
  YScale 0.25
  Patch TMP001, 0, 0
  {
  }
}

texture MGTX001, 16, 8
{
  XScale 0.25
  YScale 0.25
  Patch MGTX001, 0, 0
  {
  }
}

texture MGTX002, 64, 32
{
  XScale 0.25
  YScale 0.25
  Patch MGTX002, 0, 0
  {
  }
}

texture MGTX004, 40, 27
{
  XScale 0.25
  YScale 0.25
  Patch MGTX004, 0, 0
  {
  }
}

texture MGTX005, 8, 27
{
  XScale 0.25
  YScale 0.25
  Patch MGTX005, 0, 0
  {
  }
}

texture MGTX006, 128, 31
{
  XScale 0.25
  YScale 0.25
  Patch MGTX006, 0, 0
  {
  }
}

texture MGTX006B, 8, 31
{
  XScale 0.25
  YScale 0.25
  Patch MGTX006B, 0, 0
  {
  }
}

texture MGTX007H, 39, 4
{
  XScale 0.25
  YScale 0.25
  Patch MGTX007H, 0, 0
  {
  }
}

texture MGTX007V, 4, 39
{
  XScale 0.25
  YScale 0.25
  Patch MGTX007V, 0, 0
  {
  }
}

texture MGTX008, 14, 10
{
  XScale 0.25
  YScale 0.25
  Patch MGTX008, 0, 0
  {
  }
}

texture MGTX009, 32, 21
{
  XScale 0.25
  YScale 0.25
  Patch MGTX009, 0, 0
  {
  }
}

texture MGTX010, 13, 3
{
  XScale 0.25
  YScale 0.25
  Patch MGTX010, 0, 0
  {
  }
}

texture MGTX011A, 8, 5
{
  XScale 0.25
  YScale 0.25
  Patch MGTX011A, 0, 0
  {
  }
}

texture MGTX011B, 8, 5
{
  XScale 0.25
  YScale 0.25
  Patch MGTX011B, 0, 0
  {
  }
}

texture MGTX012, 4, 2
{
  XScale 0.25
  YScale 0.25
  Patch MGTX012, 0, 0
  {
  }
}

texture MGTX013, 19, 27
{
  XScale 0.25
  YScale 0.25
  Patch MGTX013, 0, 0
  {
  }
}

texture MGTX014R, 5, 26
{
  XScale 0.25
  YScale 0.25
  Patch MGTX014R, 0, 0
  {
  }
}

texture MGTX014L, 5, 26
{
  XScale 0.25
  YScale 0.25
  Patch MGTX014L, 0, 0
  {
  }
}

texture MGTX015, 45, 10
{
  XScale 0.25
  YScale 0.25
  Patch MGTX015, 0, 0
  {
  }
}

texture MGTX016, 14, 4
{
  XScale 0.25
  YScale 0.25
  Patch MGTX016, 0, 0
  {
  }
}

texture MGTX017, 34, 12
{
  XScale 0.5
  YScale 0.5
  Patch MGTX017, 0, 0
  {
  }
}

texture MGTX018, 50, 30
{
  XScale 0.31
  YScale 0.31
  Patch MGTX018, 0, 0
  {
  }
}

texture MGTX019, 16, 72
{
  XScale 0.25
  YScale 0.25
  Patch MGTX019, 0, 0
  {
  }
}

texture MGTX020, 8, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX020, 0, 0
  {
  }
}

texture MGTX021, 8, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX021, 0, 0
  {
  }
}

texture MGTX022, 34, 16
{
  XScale 0.25
  YScale 0.25
  Patch MGTX022, 0, 0
  {
  }
}

texture MGTX023, 34, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX023, 0, 0
  {
  }
}

texture MGTX024, 8, 56
{
  XScale 0.25
  YScale 0.25
  Patch MGTX024, 0, 0
  {
  }
}

texture MGTX025, 8, 56
{
  XScale 0.25
  YScale 0.25
  Patch MGTX025, 0, 0
  {
  }
}

texture MGTX026, 16, 16
{
  XScale 0.25
  YScale 0.25
  Patch MGTX026, 0, 0
  {
  }
}

texture MGTX027, 16, 16
{
  XScale 0.25
  YScale 0.25
  Patch MGTX027, 0, 0
  {
  }
}


texture MGTX028, 8, 72
{
  XScale 0.25
  YScale 0.25
  Patch MGTX028, 0, 0
  {
  }
}

texture MGTX029, 8, 72
{
  XScale 0.25
  YScale 0.25
  Patch MGTX029, 0, 0
  {
  }
}

texture MGTX030, 16, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX030, 0, 0
  {
  }
}

texture MGTX031, 34, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX031, 0, 0
  {
  }
}

texture MGTX032, 34, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX032, 0, 0
  {
  }
}

texture MGTX033, 34, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX033, 0, 0
  {
  }
}

texture MGTX034, 8, 72
{
  XScale 0.25
  YScale 0.25
  Patch MGTX034, 0, 0
  {
  }
}

texture MGTX035, 8, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX035, 0, 0
  {
  }
}

texture MGTX036, 8, 16
{
  XScale 0.25
  YScale 0.25
  Patch MGTX036, 0, 0
  {
  }
}

texture MGTX037, 8, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX037, 0, 0
  {
  }
}

texture MGTX038, 42, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX038, 0, 0
  {
  }
}

texture MGTX038U, 42, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX038U, 0, 0
  {
  }
}

texture MGTX039, 32, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX039, 0, 0
  {
  }
}

texture MGTX039U, 32, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX039U, 0, 0
  {
  }
}

texture MGTX040U, 78, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX040U, 0, 0
  {
  }
}

texture MGTX040, 78, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX040, 0, 0
  {
  }
}

texture MGTX040I, 64, 33
{
  XScale 0.25
  YScale 0.25
  Patch MGTX040I, 0, 0
  {
  }
}

texture MGTX041, 24, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX041, 0, 0
  {
  }
}

texture MGTX041U, 24, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX041U, 0, 0
  {
  }
}

texture MGTX042, 16, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX042, 0, 0
  {
  }
}

texture MGTX042U, 16, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX042U, 0, 0
  {
  }
}

texture MGTX043, 24, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX043, 0, 0
  {
  }
}

texture MGTX043U, 24, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX043U, 0, 0
  {
  }
}

texture MGTX044, 32, 48
{
  XScale 0.25
  YScale 0.25
  Patch MGTX044, 0, 0
  {
  }
}

texture MGTX044U, 32, 24
{
  XScale 0.25
  YScale 0.25
  Patch MGTX044U, 0, 0
  {
  }
}

texture MGTX045A, 32, 64
{
  XScale 0.25
  YScale 0.25
  Patch MGTX045A, 0, 0
  {
  }
}

texture MGTX046, 32, 46
{
  XScale 0.25
  YScale 0.25
  Patch MGTX046, 0, 0
  {
  }
}

texture TS1CAR7, 660, 100
{
  XScale 10.0
  YScale 10.0
  Patch TS1CAR7, 0, 0
  {
  }
}

texture TS1LIT1, 16, 204
{
  XScale 2.0
  YScale 2.0
  Patch TS1LIT1, 0, 0
  {
  }
}

texture TS2WAL6, 36, 288
{
  XScale 2.0
  YScale 2.0
  Patch TS2WAL6, 0, 0
  {
  }
 }

texture CTCHAIR1, 82, 40
{
  XScale 0.85
  YScale 0.85
  Patch CTCHAIR1, 0, 0
  {
  }
}

texture CTCHAIR2, 82, 40
{
  XScale 0.85
  YScale 0.85
  Patch CTCHAIR2, 0, 0
  {
  }
}

texture CTFOYLD1, 128, 77
{
  XScale 0.75
  YScale 0.75
  Patch CTFOYLD1, 0, 0
  {
  }
}

texture CTFOYLD2, 128, 93
{
  XScale 0.45
  YScale 0.45
  Patch CTFOYLD2, 0, 0
  {
  }
}

texture CTFOYLD3, 88, 49
{
  XScale 0.60
  YScale 0.60
  Patch CTFOYLD3, 0, 0
  {
  }
}

texture CTFOYLN1, 128, 77
{
  XScale 0.75
  YScale 0.75
  Patch CTFOYLN1, 0, 0
  {
  }
}

texture CTFOYLN2, 128, 93
{
  XScale 0.45
  YScale 0.45
  Patch CTFOYLN2, 0, 0
  {
  }
}

texture CTFOYLN3, 88, 49
{
  XScale 0.60
  YScale 0.60
  Patch CTFOYLN3, 0, 0
  {
  }
}

texture CTCURT1, 37, 96
{
  XScale 0.75
  YScale 0.75
  Patch CTCURT1, 0, 0
  {
  }
}

texture CTCURT2, 37, 96
{
  XScale 0.75
  YScale 0.75
  Patch CTCURT2, 0, 0
  {
  }
}

texture CTDOORL, 36, 72
{
  XScale 1.25
  YScale 1.25
  Patch CTDOORL, 0, 0
  {
  }
}

texture CTDOORR, 36, 72
{
  XScale 1.25
  YScale 1.25
  Patch CTDOORR, 0, 0
  {
  }
}
